### ISSUE TITLE
Easier container builds

### ISSUE THREAD

**Issue by robnagler** [radiasoft/containers#14]
@mrakitin, do you think you'll have to change SRW frequently? I'm concerned we'll be rebuilding radiasoft/beamsim too frequently. It takes hours now, because it contains all codes. 

One alternative is to create RPMs for the codes. However, that defeats the purpose of containers. 

Any thoughts?

**Comment by mrakitin** [comment]
In general, the changes in SRW repo should not be very frequent, but as we implement the importer, sometimes it requires some tuning, so there may be some minor changes which I can include mostly in `srwlib.py` and `srwl_bl.py`. Maybe instead of building new containers from SRW repo each time, it’s simpler to just have these two files in Sirepo repository (and synchronize them periodically) or to just copy them to `~/.pyenv/versions/2.7.10/lib/python2.7/site-packages/` as a patch?

**Comment by bruhwile** [comment]
It seems to me that RPMs don't defeat the purpose of containers.
One would think that extra step shouldn't be necessary, but I see no harm
in it if it solves a problem.
Alternatively, we could have a simpler SRW+Sirepo container.

David

**Comment by robnagler** [comment]
When I say RPMs defeat the purpose, what I mean is the "simplicity of
creating containers" is defeated. Making RPMs is non-trivial then knowing
where they are to import.

I don't think keeping individual files around is a good idea. We could add
"codes.sh srw" in the sirepo container for the time being. I may do that
for this build. People using radiasoft/beamsim aren't likely to need the
changes we need for the importer. If they are using vagrant, it's an easy
update.

**Comment by robnagler** [comment]
The "codes srw" is working fine. No need for anything else right now.
