### ISSUE TITLE
improved documentation of using the Beamsim Docker image/container

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/containers#81]
This is important.  I've assigned @cchall, because he has the 'new user' perspective and @robnagler because he knows everything.

The Dockerhub page should point here, instead of to Download (I think),  https://hub.docker.com/r/radiasoft/beamsim/

Also, since we are deprecating Vagrant, we should remove references from the RadiaSoft home page. The home page should be pointing here and to Dockerhub.

**Comment by robnagler** [comment]
@bruhwiler still an issue?

**Comment by bruhwiler** [comment]
@cchall  and  @ncook882 :   Is the documentation of how to use RadiaSoft containers sufficiently clear now, in your opinion?

**Comment by ncook882** [comment]
The wiki seems reasonable to me. I have not tested the more advanced commands (for example adding a downloader), but otherwise the instructions seem to make sense. @cchall may be better able to comment on certain specific instructions.

A few corrections on the github site:

- The links to `#containers` and `#requirements` do not go anywhere, and should be removed, unless additional material will be added. 


On the docker site, the following links are incorrect:

- The elegant link does not work. It may need to be changed to https://www.aps.anl.gov/Accelerator-Operations-Physics/Software#12345 (this seems to be what works for me)

- The [container source](https://github.com/radiasoft/containers/tree/master/vagrant/radiasoft/beamsim) link does not work. It should be fixed or removed.

**Comment by robnagler** [comment]
We have a fair bit of documentation now.
